-- AlterTable
ALTER TABLE `Post` MODIFY `title` VARCHAR(75) NULL,
    MODIFY `metaTitle` VARCHAR(100) NULL,
    MODIFY `slug` VARCHAR(100) NULL,
    MODIFY `summary` TINYTEXT NULL,
    MODIFY `publishedAt` TIMESTAMP(0) NULL,
    MODIFY `content` TEXT NULL,
    MODIFY `createdAt` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    MODIFY `UpdatedAt` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0);
